# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b4db79446d299c09ed723e6a0fbedb0e6125540d5d63ddddda5b537f4c07e26edd91f44db973c40e46d3aa3d95793038e2d9eddcd696393b23d56406058da9

test:
  secret_key_base: 08be8dca5a862d0c8c285946751c38e8e58a5ec5395afafb3fb6622a684dcfbe199cd046eec0687ea594a7d5b520fe67bf3b0637b50d68c47eb1cdb101c00cb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
